services:
  itau-db:
    image: postgres:latest
    container_name: itau-postgres
    environment:
      POSTGRES_DB: itau_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  itau-app:
    build: .
    container_name: itau-api-app
    ports:
      - "8080:8080"
    depends_on:
      - itau-db
    environment:
      # FORÇANDO a conexão para o service 'itau-db'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://itau-db:5432/itau_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
