estatistica:
  intervaloEmSegundos: 60

transacoes:
  limitePorMinuto: 4
  valorMaximoPorTransacao: 1000000
  valorMinimoPorTransacao: 0.01

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
spring:
  datasource:
    # ERRADO: url: jdbc:postgresql://localhost:5432/itau_db
    # CERTO:
    url: jdbc:postgresql://itau-postgres:5432/itau_db
    username: postgres
    password: password
